CR du Coding dojo du soir du 2024/10/10
swcraftlyon/swcraftlyon.github.io pull request #57
Opened 2024-10-10 19:13 UTC by jsorant

2024-10-10 21:40 UTC, blackheaven requested changes

2024-10-10 21:40 UTC, blackheaven commented on content/posts/2024-10-10-coding-dojo.md
> +- \n sans refacto des séparateurs n'était pas une bonne idée. On a rollback pour nettoyer avant de faire ça.
`\n` ?

2024-10-10 21:40 UTC, blackheaven commented on content/posts/2024-10-10-coding-dojo.md
> +Pour les confs le but est d'essayer de faire connaître ces pratiques plus largement.
```suggestion
  - Pour apprendre à coder mieux. Pour s'entrainer à accompagner les autres. 
- J'ai découvert les Meetups et ça m'a énormément aidé à progresser, à force d'y aller je suis devenu orga.
- Pour les confs le but est d'essayer de faire connaître ces pratiques plus largement.
```

2024-10-11 07:17 UTC, jsorant commented on content/posts/2024-10-10-coding-dojo.md
> +- \n sans refacto des séparateurs n'était pas une bonne idée. On a rollback pour nettoyer avant de faire ça.
j'ai précisé, ty !

2024-10-11 07:17 UTC, jsorant commented on content/posts/2024-10-10-coding-dojo.md
> +Pour les confs le but est d'essayer de faire connaître ces pratiques plus largement.
Corrigé avec des sous-puces

2024-10-11 07:19 UTC, blackheaven commented
Je  ne vois pas la différence :/

2024-10-11 07:36 UTC, blackheaven approved these changes

2024-10-11 07:36 UTC, merged